version: '2.1'

services:
  web:
    build: django_project
    command: ./utils/wait-for.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_project:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev_dodobas

  worker:
    build: django_project
    command: celery worker -A localities -l info -B -c 1
    depends_on:
      - db
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev_dodobas

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_NODENAME=rabbitmq

  db:
    image: mdillon/postgis:9.4-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGERS_PASSWORD=docker
