version: '2.1'

services:
  web:
    volumes:
      - ./django_project:/project
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev

  worker:
    volumes:
      - ./django_project:/project
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev

  scheduler:
    volumes:
      - ./django_project:/project
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev
