version: '2.1'

services:
  web:
    build:
      context: django_project
    command: ./utils/wait-for.sh db:5432 -- python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - rabbitmq

  worker:
    build: django_project
    command: ./utils/wait-for.sh db:5432 -- celery worker -A localities -l info -c 1
    depends_on:
      - db
      - rabbitmq

  scheduler:
    build: django_project
    command: celery beat -A localities -l info
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_NODENAME=rabbitmq

  db:
    image: mdillon/postgis:9.4-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGERS_PASSWORD=docker

