version: '3.3'

services:
  web:
    image: healthsites/web
    command: ./utils/wait-for.sh db:5432 -- uwsgi --ini uwsgi.ini
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_FILE=hs-secret.py
      - SERVICE_PORT=10001
    secrets:
      - hs-secret.py
    depends_on:
      - db
      - rabbitmq
    networks:
      - hs-prod-net
      - lb-net
    volumes:
      - ./media:/data/media
      - ./cache:/data/cache
      - ./logs:/data/logs
    deploy:
      replicas: 2


  worker:
    image: healthsites/web
    command: ./utils/wait-for.sh db:5432 -- celery worker -A localities -l info -c 1
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_FILE=hs-secret.py
    secrets:
      - hs-secret.py
    depends_on:
      - db
      - rabbitmq
    networks:
      - hs-prod-net
    volumes:
      - ./media:/data/media
      - ./cache:/data/cache
      - ./logs:/data/logs
    deploy:
      replicas: 1


  scheduler:
    image: healthsites/web
    command: celery beat -A localities -l info
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - SECRET_FILE=hs-secret.py
    secrets:
      - hs-secret.py
    depends_on:
      - db
      - rabbitmq
    networks:
      - hs-prod-net
    volumes:
      - ./logs:/data/logs
    deploy:
      replicas: 1


  smtp:
    image: catatnight/postfix
    environment:
      - maildomain=healthsites.io
      - smtp_user=noreply:docker
    networks:
      - hs-prod-net
    deploy:
      replicas: 1

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_NODENAME=rabbitmq
    networks:
      - hs-prod-net
    deploy:
      replicas: 1

  db:
    image: mdillon/postgis:9.4-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGERS_PASSWORD=docker
      - POSTGRES_DB=base_db
    networks:
      - hs-prod-net
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    deploy:
      replicas: 1

secrets:
  hs-secret.py:
    external: true

networks:
  hs-prod-net:
    external: true
  lb-net:
    external: true
